model = "gpt-5.5"
model_reasoning_effort = "xhigh"
approval_policy = "on-request"
approvals_reviewer = "user"
sandbox_mode = "read-only"

[projects."/home/leopoldguyot/dev/QFeaturesGUI"]
trust_level = "trusted"

[projects."/home/leopoldguyot"]
trust_level = "trusted"

[projects."/home/leopoldguyot/.dotfiles"]
trust_level = "trusted"

[projects."/home/leopoldguyot/dev/downstreamSCP"]
trust_level = "trusted"

[projects."/home/leopoldguyot/dev/QFeaturesPoster2026"]
trust_level = "trusted"

[tui]
theme = "monokai-extended-bright"

[tui.model_availability_nux]
"gpt-5.5" = 4

[notice.model_migrations]
"gpt-5.3-codex" = "gpt-5.4"
